### ISSUE TITLE
For grayscale image

### ISSUE THREAD

**Issue by noringname** [cuiziteng/Illumination-Adaptive-Transformer#19]
Hi, thanks for your excellent work, I want to use the model for a grayscale dataset, any suggestions on how to modify the code? It's easy to modify the local branch, but how to modify the global branch, for example, the 3*3 color matrix, how to modify that part?

**Comment by cuiziteng** [comment]
If the target GT image also 1 channel, maybe you could directly take off colour matrix (because gray scale image don't need colour process information), if the target GT image is 3 channel, this is an interesting image colorization task, and I think you could design several ways for that task to modify the colour matrix (i.e. interpolate colour palette in global branch).
